# Generated by Django 2.1.5 on 2020-06-24 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('type', models.PositiveSmallIntegerField(choices=[(1, 'dogs'), (2, 'cats'), (3, 'parrots')], default=1)),
                ('breed', models.TextField(default='')),
                ('datearrival', models.DateField()),
                ('host', models.TextField(default='')),
                ('image', models.ImageField(blank=True, upload_to='pet_avatars/%Y/%m/%d')),
            ],
        ),
        migrations.CreateModel(
            name='Shelter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('address', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='pets',
            name='shelter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Shelter'),
        ),
    ]
